repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies:
          [
            'types-all',
            'pydantic',
            'types-pymongo',
            'types-requests',
            'types-pytest',
          ]
        args: [--strict, --ignore-missing-imports]

  # Updated to the official psf/black repo instead of pre-commit/mirrors-black
  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        args: [--line-length=100]

  - repo: https://github.com/pycqa/pylint
    rev: v3.0.3
    hooks:
      - id: pylint
        args:
          [
            "--disable=missing-docstring",
            "--enable=typing",
            "--load-plugins=pylint.extensions.typing"
          ]

  - repo: https://github.com/python/pytype
    rev: 2024.2.27
    hooks:
      - id: pytype
        args: ["--jobs=4"]

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        args: ["--typeguard-packages=src.note_gen"]

  - repo: local
    hooks:
      - id: type-coverage
        name: type-coverage
        entry: python scripts/check_type_coverage.py
        language: system
        pass_filenames: false
        always_run: true