# .github/workflows/type-check.yml
name: Type Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mypy types-setuptools
      
      - name: Run mypy
        run: |
          mypy .
        
      # Optional: Add coverage reporting
      - name: Upload type coverage
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: type-coverage
          path: .mypy_cache/
